name: Integration to NCR

on:
  push:
    branches: [dev, prod, main]

env:
  IMAGE_TAG: ${{ github.sha }}
  APP_NAME: kube-test-server-${{ github.ref_name }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set dynamic APP_NAME
        run: echo "APP_NAME=kube-test-server-${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Build auth setting
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCR_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.NCR_REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}, ${{ secrets.NCR_REGISTRY }}/${{ env.APP_NAME }}:latest
